plugins {
    id 'com.gradleup.shadow'
}

architectury {
    platformSetupLoomIde()
    fabric()
}

configurations {
    common {
        canBeResolved = true
        canBeConsumed = false
    }
    compileClasspath.extendsFrom common
    runtimeClasspath.extendsFrom common
    developmentFabric.extendsFrom common

    shadowBundle {
        canBeResolved = true
        canBeConsumed = false
    }
}

dependencies {
    implementation "net.fabricmc:fabric-loader:$rootProject.fabric_loader_version"
    implementation project(':common')

    shadowBundle project(path: ':common', configuration: 'transformProductionFabric')
}

processResources {
    inputs.property 'mod_version', project.mod_version
    inputs.property 'fabric_loader_version', project.fabric_loader_version

    filesMatching('fabric.mod.json') {
        expand mod_version: inputs.properties.mod_version,
                fabric_loader_version: inputs.properties.fabric_loader_version
    }
}

shadowJar {
    configurations = [project.configurations.shadowBundle]
    archiveClassifier = 'dev-shadow'
}