# Done to increase the memory available to Gradle.
org.gradle.jvmargs=-Xmx4G
org.gradle.parallel=true

# Mod properties
mod_version=1.2.0
maven_group=net.justmili
archives_name=shulkersinbundles
display_name = ShulkersInBundles
enabled_platforms=fabric,forge,neoforge

# Minecraft properties
minecraft_version = 26.1
min_minecraft_version = 26.1

# Dependencies
fabric_loader_version = 0.18.4
forge_version = 26.1-62.0.2
forge_version_range = 62
neoforge_version = 26.1.0.1-beta
neo_version_range = 26.1