# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx4G
org.gradle.parallel=true
org.gradle.configuration-cache=false

# Fabric Properties
minecraft_version=26.2-snapshot-3
short_mcv = 26.2s
loader_version=0.19.2
loom_version=1.15-SNAPSHOT

# Mod Properties
mod_version=1.2.1
maven_group=net.justmili.shulkersinbundles
archives_base_name=ShulkersInBundles