modLoader = "javafml"
loaderVersion = "[2,)"
issueTrackerURL = ""
license = "MIT"

[[mods]]
modId = "shulkersinbundles"
version = "${mod_version}"
displayName = "Shulkers In Bundles"
authors = "JustMili"
description = '''
Making bundles a little bit more convenient and useful by allowing to put shulkers in them
'''
logoFile = "icon.png"

[[dependencies.shulkersinbundles]]
modId = "neoforge"
type = "required"
versionRange = "[${neo_version_range},)"
ordering = "NONE"
side = "BOTH"

[[dependencies.shulkersinbundles]]
modId = "minecraft"
type = "required"
versionRange = "[26.1,]"
ordering = "NONE"
side = "BOTH"

[[mixins]]
config = "shulkersinbundles.mixins.json"
